---
  - name: install nginx
    apt: name=nginx state=present update_cache=yes
    notify:
      - start nginx

  - name: copy nginx.conf
    become: yes
    template: src=process/nginx/templates/config.j2 dest=/etc/nginx/nginx.conf owner=root group=root
    tags: nginx

  - name: ensure default nginx has been deleted
    become: yes
    file: dest=/etc/nginx/sites-enabled/default state=absent

  - name: restart nginx
    become: yes
    service: name=nginx state=restarted enabled=yes
    tags: nginx
    notify:
      - restart nginx
